[project]
name = "effective-garbanzo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "gpiozero>=2.0.1",
    "pirc522",
    "pygame>=2.6.1",
    "spidev",
]

[tool.uv.sources]
pirc522 = { git = "https://github.com/hoffie/pi-rc522-gpiozero" }
